apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-deployment
  labels:
    app: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:next # Será reemplazada por GCR en el pipeline
        env:
          - name: DB_ADAPTER
            value: postgres
          - name: DB_HOST
            value: kong-database
          - name: DB_USER
            value: kong
          - name: TOKEN_SECRET
            value: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb # ¡ADVERTENCIA! Usar Secrets
          - name: DB_DATABASE
            value: konga_db
          - name: NODE_ENV
            value: production
        ports:
          - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: konga-service
spec:
  type: ClusterIP
  selector:
    app: konga
  ports:
    - port: 1337
      targetPort: 1337