apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      # Init Container para esperar que las migraciones terminen
      containers:
      - name: kong
        image: kong:latest # Será reemplazada por GCR en el pipeline
        env:
          - name: KONG_PG_HOST
            value: kong-database
          - name: KONG_PROXY_LISTEN
            value: 0.0.0.0:8000
          - name: KONG_PROXY_LISTEN_SSL
            value: 0.0.0.0:8443
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001
        ports:
          - containerPort: 8000
          - containerPort: 8443
          - containerPort: 8001
        # NOTA: Se asume que las migraciones se ejecutarán manualmente o en otro InitContainer
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: ClusterIP
  selector:
    app: kong
  ports:
    - name: proxy-http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: admin-api
      protocol: TCP
      port: 8001
      targetPort: 8001