name: Despliegue de Kong y Konga a GKE Auto

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE_REGISTRY: gcr.io
  KONG_IMAGE_NAME: kong-gateway
  KONGA_IMAGE_NAME: konga-gui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Autenticaci√≥n en Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Clave de la Cuenta de Servicio (secreta)
          
      # 2. Configuraci√≥n de GKE
      - name: Configurar gcloud y kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          # Asegura que las credenciales est√©n disponibles para Docker y kubectl
          setup_gcloud: true 

      # 3. Autenticar en Google Container Registry (GCR)
      - name: Autenticaci√≥n en GCR
        run: gcloud auth configure-docker ${{ env.IMAGE_REGISTRY }}

      # 4. Construir y Etiquetar Im√°genes 
      - name: Construir y etiquetar Kong
        run: |
          docker pull kong:latest
          docker tag kong:latest ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONG_IMAGE_NAME }}:latest
      
      - name: Construir y etiquetar Konga
        run: |
          docker pull pantsel/konga:next
          docker tag pantsel/konga:next ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONGA_IMAGE_NAME }}:latest

      # 5. Subir Im√°genes a GCR ‚¨Ü
      - name: Subir imagen de Kong a GCR
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONG_IMAGE_NAME }}:latest

      - name: Subir imagen de Konga a GCR
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONGA_IMAGE_NAME }}:latest

      # 6. Obtener Credenciales de GKE
      - name: Obtener credenciales del cluster GKE
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      
      # 7. Despliegue a GKE üöÄ
      - name: Desplegar a GKE
        run: |
          # Reemplazar la URL de la imagen en los manifiestos de K8s
          sed -i "s|image: kong:latest|image: ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONG_IMAGE_NAME }}:latest|g" k8s-manifests/kong-deployment.yaml
          sed -i "s|image: pantsel/konga:next|image: ${{ env.IMAGE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.KONGA_IMAGE_NAME }}:latest|g" k8s-manifests/konga-deployment.yaml

          # Aplicar los manifiestos de Kubernetes
          kubectl apply -n kong -f k8s-manifests/kong-db-pvc.yaml
          kubectl apply -n kong -f k8s-manifests/postgres-deployment.yaml
          kubectl apply -n kong -f k8s-manifests/postgres-service.yaml
          sleep 20
          kubectl apply -n kong -f k8s-manifests/kong-db-init-job.yaml
          sleep 20
          kubectl apply -n kong -f k8s-manifests/konga-prepare-job.yaml
          sleep 20
          kubectl apply -n kong -f k8s-manifests/kong-migrations.yaml
          sleep 20
          kubectl apply -n kong -f k8s-manifests/kong-deployment.yaml
          sleep 20
          kubectl apply -n kong -f k8s-manifests/konga-deployment.yaml

      - name: Desplegar Istio
        run: |
          # Define la versi√≥n de Istio
          export ISTIO_VERSION=1.22.2
          
          # 1. Descarga el paquete de Istio
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${ISTIO_VERSION} sh -
          
          # 2. Navega al directorio de Istio para mover istioctl
          cd istio-${ISTIO_VERSION}
          sudo mv bin/istioctl /usr/local/bin/
          
          # 3. Verifica la instalaci√≥n e instala Istio con el perfil 'default' y configuraci√≥n de Zipkin
          istioctl version
          
          istioctl install --set profile=default \
          --set meshConfig.enableTracing=true \
          --set meshConfig.extensionProviders[0].name=zipkin \
          --set meshConfig.extensionProviders[0].zipkin.service="zipkin.istio-system:9411" \
          -y
            
          # 4. Instalar Addons (Prometheus, Grafana, Kiali) y Zipkin
          kubectl apply -f samples/addons/prometheus.yaml
          kubectl apply -f samples/addons/grafana.yaml
          kubectl apply -f samples/addons/kiali.yaml
          cd ..
          kubectl apply -f k8s-manifests/zipkin.yaml
          kubectl apply -f k8s-manifests/telemetry.yaml

          # 5. Reiniciar Istiod y aplicaciones
          kubectl rollout restart deployment istiod -n istio-system
          kubectl rollout restart deployment -n kong
          
          # 6. Aplica Gateway y VirtualService
          kubectl apply -n istio-system -f k8s-manifests/istio-gateway.yaml
          kubectl apply -n istio-system -f k8s-manifests/konga-vs.yaml